#!/bin/sh

# Lock screen and block dunst messages from appear
lock() {
    # Suspend message display
    killall -SIGUSR1 dunst

    # Lock the screen
    i3lock --nofork -e -f --color '#000000'

    # Resume message display
    killall -SIGUSR2 dunst
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    poweroff)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|tlock|logout|suspend|hibernate|reboot|poweroff}"
        exit 2
esac

exit 0