# ~/.bash_aliases
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
alias df='df -hTP'
alias du='du -xk'

# Directory: list
alias ls='ls -trhF --color=tty --group-directories-first' # classify files in colour show directories on top
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #

# Directory: change
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'

# Regular Expressions: grep
alias grep='grep --color'                         # show differences in colour
alias cgrep='egrep -v "^\s*(#|;|$)" --color=auto' # strip comments from files
alias egrep='egrep --color=auto'                  # show differences in colour
alias fgrep='fgrep --color=auto'                  # show differences in colour

# Regular Expressions: awk
alias sumfile="awk 'BEGIN{s=0}{s=s+\$0}END{print s}'" # give the sum of values from a file

# Misc
alias whence='type -a'                            # where, of a sort
alias less='less -r'                              # raw control characters
alias getmp3='youtube-dl --audio-format mp3 $@'

case "$OSTYPE" in
    linux*)
		OSCODENAME=$(lsb_release -sc)
	;;
    cygwin)
		OSCODENAME="cygwin"
	;;
    *)
        ;;
esac

case "${OSCODENAME,,}" in
    twentyfive|twentysix|twentyseven)
		source ~/.bashrc.d/bash_aliases.fedora
	;;
    utopic|karmic|lucid)
		source ~/.bashrc.d/bash_aliases.ubuntu
	;;
    *)
	;;
esac
