# vim:ft=sh
# ~/.bash_aliases
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# File: misc
#
# Update source file
alias src='source ~/.bashrc'
# Go Home
alias ~="cd ~"
# Clear terminal display
alias c='clear'

# Interactive operation...
alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'
#
# Default to human readable figures
alias df='df -hTP'
alias du='du -xk'

# Directory: list
#
# Classify files in colour show directories on top
alias ls='ls -trhF --color=tty --group-directories-first'
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
# Long list
alias ll='ls -l'
# All but . and ..
alias la='ls -A'
alias l='ls -CF'

# Directory: change
#
# Go back 1 directory level (for fast typers)
alias cd..='cd ../'
# Go back 1 directory level
alias ..='cd ../'
# Go back 2 directory levels
alias ...='cd ../../'
# Go back 3 directory levels
alias .3='cd ../../../'
# Go back 4 directory levels
alias .4='cd ../../../../'
# Go back 5 directory levels
alias .5='cd ../../../../../'
# Go back 6 directory levels
alias .6='cd ../../../../../../'

# Regular Expressions: grep
#
# Show differences in colour
#alias grep='grep --color'
# Strip comments from files
#alias cgrep='egrep -v "^\s*(#|;|$)" --color=auto'
# Show differences in colour
#alias egrep='egrep --color=auto'
# Show differences in colour
#alias fgrep='fgrep --color=auto'
# Delete all lines beginning only with a # from a file and also empty lines
#alias rg_comments="egrep -v '^\s+?#|^$'"
# Show some oracle database kernel tuning
#alias rg_orasysctl="egrep 'vm.(swappiness|dirty_(background_ratio|ratio|(expire|writeback)_centisecs))'"
# Show 3rd party kernel modules
#alias rg_3rdkmodinfo="egrep '(extra|weak)'"

# Regular Expressions: pcregrep
# Install: dnf install pcre-tools
# Site: http://www.rexegg.com/regex-quickstart.html#ref
alias grep='pcregrep --color'
# Strip comments from files
alias cgrep='pcregrep -v "^\s*(#|;|$)" --color=auto'
# Show differences in colour
alias egrep='pcregrep --color=auto'
# Show differences in colour
alias fgrep='pcregrep --color=auto'
# Delete all lines beginning only with a # from a file and also empty lines
alias rg_comments="pcregrep -v '^(\s+)?(#|;)|^(\s+)?$'"
# Show some oracle database kernel tuning
alias rg_orasysctl="pcregrep 'vm.(swappiness|dirty_(background_ratio|ratio|(expire|writeback)_centisecs))'"
# Show 3rd party kernel modules
alias rg_3rdkmodinfo="pcregrep '(extra|weak)'"

# Regular Expressions: awk
#
# Delete all lines beginning with a # from a file
alias sumfile="awk 'BEGIN{s=0}{s=s+\$0}END{print s}'"
# Sum numerical matches from other outputs
alias rg_sumatch="awk '{SUM+=\$1}END{print SUM}'"
# Matches lines starting with sd and dm- and sort 10th columnt for
# number number greater than 10
alias rg_iosvctm="awk '/(dev|sd|dm-)/ { if ( \$10 > 10 ) print \$0 }'"
alias rg_ioawait="awk '/(dev|sd|dm-)/ { if ( \$9 > 10 ) print \$0 }'"

# Misc
alias whence='type -a'                            # where, of a sort
alias less='less -r'                              # raw control characters
alias getmp3='youtube-dl --audio-format mp3 $@'

case "$OSTYPE" in
    linux*)
		OSCODENAME=$(lsb_release -si)
	;;
    cygwin)
		OSCODENAME="cygwin"
	;;
    *)
        ;;
esac

case "${OSCODENAME}" in
    Fedora)
		source ~/.bashrc.d/bash_aliases.fedora
	;;
    Debian|Ubuntu)
		source ~/.bashrc.d/bash_aliases.ubuntu
	;;
    *)
	;;
esac
