# vim:ft=sh
# ~/.bash_aliases
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
alias df='df -hTP'
alias du='du -xk'

# Directory: list
#
# Classify files in colour show directories on top
alias ls='ls -trhF --color=tty --group-directories-first'
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
# Long list
alias ll='ls -l'
# All but . and ..
alias la='ls -A'
alias l='ls -CF'

# Directory: change
#
alias ..='cd ..'
alias ....='cd ../..'
alias ......='cd ../../..'

# Regular Expressions: grep
#
# Show differences in colour
alias grep='grep --color'
# Strip comments from files
alias cgrep='egrep -v "^\s*(#|;|$)" --color=auto'
# Show differences in colour
alias egrep='egrep --color=auto'
# Show differences in colour
alias fgrep='fgrep --color=auto'
# Delete all lines beginning only with a # from a file
alias rg_comments="egrep -v '^\s+?#|^$'"

# Regular Expressions: awk
#
# Delete all lines beginning with a # from a file
alias sumfile="awk 'BEGIN{s=0}{s=s+\$0}END{print s}'"
# Matches lines starting with sd and dm- and sort 10th columnt for
# number number greater than 10
alias rg_iosvctm="awk '/^(sd|dm-)/ { if ( $10 > 10 ) print $0 }'"

# Misc
alias whence='type -a'                            # where, of a sort
alias less='less -r'                              # raw control characters
alias getmp3='youtube-dl --audio-format mp3 $@'

case "$OSTYPE" in
    linux*)
		OSCODENAME=$(lsb_release -sc)
	;;
    cygwin)
		OSCODENAME="cygwin"
	;;
    *)
        ;;
esac

case "${OSCODENAME,,}" in
    twentyfive|twentysix|twentyseven)
		source ~/.bashrc.d/bash_aliases.fedora
	;;
    utopic|karmic|lucid)
		source ~/.bashrc.d/bash_aliases.ubuntu
	;;
    *)
	;;
esac
